### ISSUE TITLE
How to install the service?

### ISSUE THREAD

**Issue by a-t-0** [stuvusIT/mattermost#16]
Hi, after having a look at this project I thought it might be a quick and convenient way set up a self-hosted mattermost, and was wondering how to install the mattermost server/software in this repo (on Ubuntu 20.04).  I tried:
```
sudo apt update
sudo apt install software-properties-common
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt install ansible
conda deactivate
ansible-playbook tasks/main.yml
ansible-playbook tasks/install.yml
ansible-playbook playbook.yml (copied the one you provided for a test run)
```
However, these yield errors, which seem to suggest I am not installing it correctly. Hence, I was curious whether you would perhaps be so kind to include an installation instruction?

**Comment by Scriptkiddi** [comment]
sorry we switched from mattermost to matrix, so this has not been used in a while

**Comment by Scriptkiddi** [comment]
you should setup an ansible inventory and configure my example on that particular host

**Comment by a-t-0** [comment]
Thank you for your quick response and suggestion!
